version: '3'

services:
  ot-sim:
    image: ot-sim
    command: ot-sim-cpu-module /root/local-ot-sim/config/halucinator-example/test.xml
    ports:
      - 8000:1880
    volumes:
      - ${PWD}/..:/root/local-ot-sim:rw
      - halucinator-ipc-tmp:/tmp

  halucinator_openplc:
    image: halucinator_openplc
    command: /root/halucinator/openplc_demo/openplc_run.sh
    volumes:
      - halucinator-ipc-tmp:/tmp
    # we need stdio and tty for interacting with halucinator debugger for demo
    stdin_open: true
    tty: true

volumes:
  halucinator-ipc-tmp:
