version: '3'

services:
  ot-sim:
    image: ot-sim
    command: ot-sim-cpu-module /root/local-ot-sim/config/halucinator-example/test.xml
    volumes:
      - ${PWD}/..:/root/local-ot-sim:ro
      - halucinator-ipc-tmp:/tmp

  halucinator_openplc:
    image: halucinator_openplc
    command: /root/halucinator/openplc_demo/openplc_run.sh
    volumes:
      - halucinator-ipc-tmp:/tmp

volumes:
  halucinator-ipc-tmp:
